Update man page and README to clarify the --group option
RedHatInsights/insights-client pull request #157
Opened 2023-12-08 17:24 UTC by m8ram

This update is a first step to address #156 it simply updates the man page and the README to clarify what the option currently does.

2023-12-18 16:24 UTC, ahitacat requested changes
I will also suggest to make such changes in insights-core. In insights-core are defined the parameters of the cli tool, so when use the `--help` parameter it will show this information update and correct.

2023-12-22 09:23 UTC, ahitacat requested changes

2023-12-22 09:23 UTC, ahitacat commented on README.md
> +- `--group=GROUP` - Add a tage named group to the system in the insights web UI.
```suggestion
- `--group=GROUP` - Add a tag named `group` to the system in the insights web UI and in insights-client tags file.
```

2023-12-22 09:23 UTC, ahitacat commented on docs/insights-client.8
> +Add a tag name group with the specified value to this host. The tag will be saved to the tags file.
```suggestion
Add a tag named `group` with the specified value to this host. The tag will be saved to the tags file.
```

2024-01-02 10:02 UTC, ptoscano commented on README.md
> +- `--group=GROUP` - Add a tage named group to the system in the insights web UI.
also typo "tage"

2024-03-08 16:05 UTC, ptoscano commented
/packit build

2024-03-08 16:19 UTC, ptoscano approved these changes
LGTM, thanks!

2024-03-11 05:25 UTC, merged