Condtionally build ros subpackage
RedHatInsights/insights-client pull request #164
Opened 2024-02-07 14:42 UTC by subpop

Only build the ros subpackage when rpmbuild is invoked with the "--with ros" flag.

2024-02-07 14:51 UTC, ptoscano requested changes
Other than the spec syntax issue, there's the "condtionally" typo in both the PR title and the commit message.

2024-02-07 14:51 UTC, ptoscano commented on insights-client.spec
> +rpmbuild. The default behavior is to build without it.
missing comment character here, which breaks the build

2024-02-07 15:28 UTC, ptoscano commented on insights-client.spec
> +%{endif}
```suggestion
%endif
```

2024-02-07 15:28 UTC, ptoscano commented on insights-client.spec
> +%{endif}
```suggestion
%endif
```

2024-02-07 15:28 UTC, ptoscano commented on insights-client.spec
> +%{endif}
```suggestion
%endif
```

2024-02-09 18:56 UTC, subpop commented
I fixed the typos and added an empty `%files ros` section, which I discovered is required in order to actually create the RPM.

2024-02-14 12:35 UTC, ptoscano commented
/packit test

2024-02-14 12:35 UTC, ptoscano commented
/packit build

2024-02-14 13:39 UTC, merged