feat: simulate packit setup for non-packit testing
RedHatInsights/insights-client pull request #189
Opened 2024-03-07 23:42 UTC by Lorquas

This will aid in downstream testing, eg: beaker, running testing-farm directly, running tmt directly, locally in a container, etc...

2024-03-08 06:01 UTC, ptoscano requested changes
generally OK, some things to tweak

2024-03-08 17:20 UTC, Lorquas commented on systemtest/tests/integration/test.sh
> +source <(cat /etc/os-release | grep -E "^(ID|VERSION_ID)")
Ah, it made `env` debugging faster, left it in since all the other vars are unused.  Changing...

2024-03-08 17:21 UTC, Lorquas commented on systemtest/guest-setup.sh
> +if [ ! "$(dnf search insights-client 2>&1 > /dev/null)" = "No matches found." ]; then
Much cleaner, yet slower on my systems, changing...

2024-03-08 17:59 UTC, Lorquas commented on systemtest/guest-setup.sh
> +  RELEASEVER=$(python3 -c 'import dnf, json; db = dnf.dnf.Base(); print(db.conf.substitutions["releasever"])')
Indeed I could always `| cut -d. -f1`. The problem is dnf allows `releasever` to be overwritten by rpm headers, its own db, /etc/dnf/vars - so it is a 'calculated' value.  In such cases where I don't actually care about the release version, but rather what dnf thinks the released version is I defer to this hack.  This only really fixes problems in beaker between releases, so I could go either way on this one.

2024-03-08 17:59 UTC, Lorquas commented on systemtest/guest-setup.sh
> +  rpm --import https://download.copr.fedorainfracloud.org/results/@yggdrasil/latest/pubkey.gpg
changing.

2024-03-08 17:59 UTC, Lorquas commented on systemtest/tests/integration/test.sh
> +rpm -q insights-client || sh ./systemtest/guest-setup.sh
done

2024-03-11 05:42 UTC, ptoscano approved these changes

2024-03-11 05:43 UTC, merged