feat(test):  Adding betelgeuse docstrings to test_collection.py
RedHatInsights/insights-client pull request #274
Opened 2024-08-13 18:06 UTC by zpetrace

CCT-661 - Add docstrings to test_collection.py

2024-09-05 07:56 UTC, m-horky requested changes

2024-09-05 07:56 UTC, m-horky commented on integration-tests/test_collection.py
> +    :title: test Output File with Non-Existing Path
Uppercase T?

2024-09-05 07:56 UTC, m-horky commented on integration-tests/test_collection.py
> +        2. Define the parent directory path
This somehow feels excessive, does it have to be documented as a separate step?

2024-09-05 07:56 UTC, m-horky commented on integration-tests/test_collection.py
> +        4. Verify the error message is appropriate and as expected
Should this step be more specific? `Verify the error message says they can't be used together` or something?

2024-09-05 07:56 UTC, m-horky commented on integration-tests/test_collection.py
> +    :title: Test output File with Relative Path
This capitalization looks strange to me, is it on purpose?

2024-09-05 07:56 UTC, m-horky commented on integration-tests/test_collection.py
> +        4. Verify the error message is as expected
Again -- is "as expected" descriptive enough, or should this say that `The error message says that `--output` cannot be used with a directory?

2024-09-05 07:56 UTC, m-horky commented on integration-tests/test_collection.py
> +        3. Verify that the command creates an archive file with the directory name plus
...`plus extension`?

2024-09-05 07:56 UTC, m-horky commented on integration-tests/test_collection.py
> +        1. The dorectory is set correctly
directory

2024-09-18 10:37 UTC, zpetrace commented
Again, I have changed the capitalization to be more consistent, sorry for the confusion, other than that I have made some smaller changes, so you can go over it:)

2024-09-18 12:49 UTC, m-horky approved these changes

2024-09-18 14:22 UTC, ptoscano requested changes
it seems generally ok, i left various notes

to catch the typos, i recommend to use `codespell` and run it in the files you are editing

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test output file with valid parameters
maybe spell out `--output-file` here as well?

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test output file with non-existing path
ditto

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test output directory without specifying a path
ditto

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: test output specifying both directory and file
ditto; also, missed Capitalization to the beginning of the title

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test output file with relative path
ditto

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test output directory with non-empty directory
ditto

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test output directory creates archive for directory
ditto; also this ought to mention `--output-file`, not directory

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test output file already exists
ditto

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +        4. The error message indicates that the file aready exists
typo "aready"

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test CMD timeout configuration
i'd mention the option explicitly, rather than "CMD timeout"

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +        3. Run insights-client with a command that would take lomger than the
typo "lomger"

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +        5. Verify that the output includes expected message
"... includes _the_ expected ..."

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +        5. The outpus is as expected
typo "outpus"

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +        5. The outpus is as expected
i'd clarify what is "expected" here: an error message? something else?

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +    :title: Test branch info includes all required information
i'd explicitly mention "the branch_info file"

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +        4. Inspect the branch_info file to verify it containes correct values
typo "containes"

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +        3. The latest archive should be successfully extracted
better than "should be", "is"

2024-09-18 14:22 UTC, ptoscano commented on integration-tests/test_collection.py
> +        correct directory structure and contains all the necessary dirs and subdirs
spell out "dirs" and "subdirs" explicitly: "directories", "subdirectories"; it is less colloquial, and will be better in testing documents

2024-09-19 07:49 UTC, ptoscano approved these changes

2024-09-19 07:57 UTC, merged