test: add insights-clilent test case for tags
RedHatInsights/insights-client pull request #293
Opened 2024-09-26 10:58 UTC by zhangqianqian

This PR test how the tags generated, and check the tags on inventory.

2024-09-27 08:52 UTC, m-horky reviewed
Generally LGTM from my point of view.

2024-09-27 08:52 UTC, m-horky commented on integration-tests/test_tags.py
> +    insights_client.run()
This shouldn't be necessary, `--group` already performs a collection.

2024-09-27 12:57 UTC, zhangqianqian commented
> Generally LGTM from my point of view. Also, there's a typo in the title, `clilent`.

Thanks, has modified the PR title. @m-horky would you pls help merge it?

2024-09-27 13:13 UTC, m-horky commented on integration-tests/test_tags.py
> +        os.remove("/etc/insights-client/tags.yaml")
Should this happen _before_ the registration? If some test left the file there, the only-satellite-tags below assert would fail.

2024-09-27 13:13 UTC, m-horky commented on integration-tests/test_tags.py
> +    assert system_tags[-1]["value"] == "first_tag"
Is the order of tags guaranteed? Doing it without relying on that should be simple:
```py
assert {"namespace": "insights-client", "key": "group", "value": "first_tag"} in system_tags
```

2024-09-27 13:13 UTC, m-horky commented on integration-tests/test_tags.py
> +    assert system_tags[-1]["value"] == "second_tag"
Same as above.

2024-09-29 03:25 UTC, zhangqianqian commented
@m-horky modified the PR again as your suggestions. pls merge it.

2024-10-03 19:28 UTC, ptoscano requested changes
Thanks for the test! It seems to work fine, there are few small things to fix.

---------------

Since this is a new test, please write a proper docstring for it following the format of Testimony [1]; see also the internal CCT-657 and all the recent PRs done by Zdenek on the topic.

[1] https://testimony-qe.readthedocs.io/en/stable/

---------------

There is a lot of repetition of the path `/etc/insights-client/tags.yaml` all around the test, and lots of manual I/O: let's simplify it using `pathlib.Path`; declate it as global variable in `constants.py`:
```python
import pathlib

[...]
TAGS_FILE = pathlib.Path("/etc/insights-client/tags.yaml")
```
Then it can be used easily -- few examples:
```python
    with contextlib.suppress(FileNotFoundError):
        TAGS_FILE.unlink()
[...]
        assert not TAGS_FILE.exists()
[...]
    with TAGS_FILE.open("r") as tags_yaml:
```

---------------

Do not forget to remove the tags file at the end of the test; to make sure to remove it even in case the test fails, you can use `contextlib.ExitStack()`:
```python
    with contextlib.ExitStack() as stack:
        # Run insights-client --group
        insights_client.run("--group=first_tag")
        stack.callback(os.remove, TAGS_FILE)

        [the rest of the test until the end]
```

---------------

2024-10-14 11:01 UTC, zhangqianqian commented
> Thanks for the test! It seems to work fine, there are few small things to fix.
> 
> Since this is a new test, please write a proper docstring for it following the format of Testimony [1]; see also the internal CCT-657 and all the recent PRs done by Zdenek on the topic.
> 
> [1] https://testimony-qe.readthedocs.io/en/stable/
> 
> There is a lot of repetition of the path `/etc/insights-client/tags.yaml` all around the test, and lots of manual I/O: let's simplify it using `pathlib.Path`; declate it as global variable in `constants.py`:
> 
> ```python
> import pathlib
> 
> [...]
> TAGS_FILE = pathlib.Path("/etc/insights-client/tags.yaml")
> ```
> 
> Then it can be used easily -- few examples:
> 
> ```python
>     with contextlib.suppress(FileNotFoundError):
>         TAGS_FILE.unlink()
> [...]
>         assert not TAGS_FILE.exists()
> [...]
>     with TAGS_FILE.open("r") as tags_yaml:
> ```
> 
> Do not forget to remove the tags file at the end of the test; to make sure to remove it even in case the test fails, you can use `contextlib.ExitStack()`:
> 
> ```python
>     with contextlib.ExitStack() as stack:
>         # Run insights-client --group
>         insights_client.run("--group=first_tag")
>         stack.callback(os.remove, TAGS_FILE)
> 
>         [the rest of the test until the end]
> ```

Thanks Pino.

2024-10-22 06:07 UTC, ptoscano approved these changes
```
integration-tests/test_tags.py::test_tags PASSED                         [ 92%]
```
thanks!

2024-10-22 06:07 UTC, merged